# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Verify"
  lane :verify do |options|
    branch = options[:branch] || "main"
    project = "CameraToolKit"
    skipImportValidation = options[:skipImportValidation]
    ensure_git_branch(branch: branch)
    pod_lib_lint(
      allow_warnings: true,
      use_libraries: true,
      use_modular_headers: true,
      # 跳过验证 pod 是否可以导入
      skip_import_validation: skipImportValidation
    )
  end
end

platform :ios do
  desc "发布组件"
  lane :deploy do |options|
    branch = options[:branch] || "main"
    project = "CameraToolKit"
    skipImportValidation = options[:skipImportValidation]
  
    ensure_git_branch(branch: branch)
    pod_lib_lint(
      allow_warnings: true,
      use_libraries: true,
      use_modular_headers: true,
      # 跳过验证 pod 是否可以导入
      skip_import_validation: skipImportValidation,
      sources: ["https://github.com/CocoaPods/Specs"]
    )
    version = version_bump_podspec(path: "#{project}.podspec")
    git_commit(path: "./*.podspec", message: "Release to version #{version}")
    add_git_tag(tag: version)
    push_to_git_remote(remote_branch: branch, force: false, tags: true)
    # changelog = changelog_from_git_commits
    # sh("git fetch --tags")
    pod_push(
      path: "#{project}.podspec",
      allow_warnings: true,
      # 跳过验证 pod 是否可以导入
      skip_import_validation: skipImportValidation,
      verbose: true
    )
  end
end
